### ISSUE TITLE
Curly braces fail output

### ISSUE THREAD

**Issue by DixonDs** [SharpeRAD/Cake.Powershell#25]
The issue https://github.com/SharpeRAD/Cake.Powershell/issues/18 is reproducible again, I guess after this PR was merged: https://github.com/SharpeRAD/Cake.Powershell/pull/23

The new exception stacktrace:
```
 System.Management.Automation.CmdletInvocationException: Input string was not in a correct format. ---> System.FormatException: Input string was not in a correct format.
    at Cake.Diagnostics.Formatting.FormatParser.ParseProperty(TextReader reader)
    at Cake.Diagnostics.Formatting.FormatParser.<Parse>d__0.MoveNext()
    at Cake.Diagnostics.CakeBuildLog.Write(Verbosity verbosity, LogLevel level, String format, Object[] args)
    at Cake.Powershell.CakePSHostInterface.WriteLine(String value)
    at Microsoft.PowerShell.Commands.Internal.Format.ConsoleLineOutput.OnWriteLine(String s)
    at Microsoft.PowerShell.Commands.Internal.Format.ConsoleLineOutput.WriteLine(String s)
    at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteSingleLineHelper(String prependString, String line, LineOutput lo)
    at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperty(Int32 k, String propertyValue, LineOutput lo)
    at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperties(String[] values, LineOutput lo)
    at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ListOutputContext.ProcessPayload(FormatEntryData fed)
    at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessPayload(FormatEntryData fed, OutputContext c)
    at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessObject(PSObject so)
    at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by SharpeRAD** [comment]
Going to close this now, feel free to reopen it if you are still experiencing an issue.
