### ISSUE TITLE
Can't Install Cake.Powershell with Cake .0.30.0 global .NET CLI tool

### ISSUE THREAD

**Issue by jmcmillen** [SharpeRAD/Cake.Powershell#68]
Hi,

I'm getting an install error when using Cake.Powershell in a build script that's called from the new .NET CLI tool. 

### Steps To Reproduce
```
#addin nuget:?package=Cake.Powershell&version=0.4.7

var target = Argument("Target", "Restore");

Task("Restore")
	.Description("Restore Nuget packages for the solution")
	.Does(() => { });

RunTarget(target);
```
Then run this command

` dotnet cake build.cake`

### Output
```
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing C:/Test/WebApplication1/build.cake...
Processing build script...
Installing addins...
Found package 'Cake.Powershell 0.4.7' in 'C:/Test/WebApplication1/tools/Addins'.
Package Cake.Powershell.0.4.7 has already been installed.
Successfully installed 'Cake.Powershell 0.4.7' to C:/Test/WebApplication1/tools/Addins
Executing nuget actions took 40.34 ms
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Powershell'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 106
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73
```

The install of Cake.Powershell works fine when using the build.ps1 powershell bootstrapper.  It's only failing when I try to use the dotnet CLI tool.

**Comment by jmcmillen** [comment]
Good to know.  Thank you.  And thanks for the quick response too!

**Comment by SharpeRAD** [comment]
Closing as framework limitation.
